trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: GitHubSecrets  # Contains your GitHub PAT

steps:
- checkout: self
  fetchDepth: 0  # Get full history
  persistCredentials: true  # Important for git operations

- script: |
    git config --global user.email "your-email@example.com"
    git config --global user.name "Azure Pipeline"
    
    # Ensure we're on main branch
    git checkout main
    
    # Debug info
    echo "Available branches:"
    git branch -a
    echo "Current branch:"
    git branch --show-current
    echo "Remote branches:"
    git ls-remote --heads    # Add or update GitHub remote
    if git remote | grep -q github; then
      git remote set-url github https://$GITHUB_PAT@github.com/YOUR_USERNAME/PurrfectMatch.git
    else
      git remote add github https://$GITHUB_PAT@github.com/YOUR_USERNAME/PurrfectMatch.git
    fi
    
    # Push all branches and tags
    git push github --all --force
    git push github --tags --force
    
    # Verify push
    git ls-remote --heads github
  displayName: 'Mirror to GitHub'
  env:
    GITHUB_PAT: $(GITHUB-TOKEN)